import { TODO_PRIORITY, TODO_STATUS } from "../../shared/constants/todo";

export const PRIORITIES = [
  TODO_PRIORITY.LOW,
  TODO_PRIORITY.MEDIUM,
  TODO_PRIORITY.HIGH,
];

export const STATUSES = [
  TODO_STATUS.TODO,
  TODO_STATUS.IN_PROGRESS,
  TODO_STATUS.COMPLETED,
];
